solidusio/solidus_subscriptions

README.md

Update Readme to correct repo

---

lib/solidus_subscriptions/testing_support/factories.rb
lib/solidus_subscriptions/testing_support/factories/installment_detail_factory.rb
lib/solidus_subscriptions/testing_support/factories/installment_factory.rb
lib/solidus_subscriptions/testing_support/factories/line_item_factory.rb
lib/solidus_subscriptions/testing_support/factories/spree/line_item_factory.rb
lib/solidus_subscriptions/testing_support/factories/spree/order_factory.rb
lib/solidus_subscriptions/testing_support/factories/spree_modification_factory.rb
lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
solidus_subscriptions.gemspec
spec/spec_helper.rb

Fix the outdated reference to `factory_girl`.

Update factory_girl to factory_bot

---

.travis.yml
app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb
app/models/solidus_subscriptions/checkout.rb
app/models/solidus_subscriptions/subscription.rb
app/models/solidus_subscriptions/subscription_line_item_builder.rb
app/views/spree/admin/shared/_no_objects_found.html.erb
app/views/spree/admin/subscriptions/_form.html.erb
app/views/spree/admin/subscriptions/_legacy_form.html.erb
app/views/spree/admin/subscriptions/edit.html.erb
app/views/spree/admin/subscriptions/index.html.erb
app/views/spree/admin/subscriptions/new.html.erb
lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
spec/controllers/solidus_subscriptions/api/v1/line_items_controller_spec.rb
spec/controllers/solidus_subscriptions/api/v1/subscriptions_controller_spec.rb
spec/controllers/spree/admin/subscriptions_controller_spec.rb
spec/helpers/checkout_infrastructure.rb
spec/lib/solidus_subscriptions/processor_spec.rb
spec/models/solidus_subscriptions/checkout_spec.rb
spec/rails_helper.rb

This PR continues the work started by @joeljackson and @fastjames in #54 with a rebased branch, fixing all the deprecation warnings the extension had as well as several failing specs so we can have a green Travis build again :tada:

Fix deprecations warnings and failing specs

---

.circleci/config.yml
README.md

This PR also adds a status Badge in the README

Run specs with CircleCI

---

app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
app/models/solidus_subscriptions/checkout.rb
app/models/solidus_subscriptions/subscription_line_item_builder.rb
app/views/spree/admin/subscriptions/index.html.erb

Removes some conditional logic that was running to support unmaintained Solidus versions.

Remove checks on unsupported Solidus versions

---

app/controllers/spree/admin/subscriptions_controller.rb
app/views/spree/admin/subscriptions/_form.html.erb
app/views/spree/admin/subscriptions/new.html.erb
config/locales/en.yml

Adds the ability for an admin to add a line item to a subscription when editing it.

Allow admins to add subscription items when editing subscription

---

app/controllers/spree/admin/installments_controller.rb
app/views/spree/admin/installments/index.html.erb

Improves the way installment dates are visualized, and adds a default sort order on descending creation date in the Installments screen.

Improve installment visualization and sorting

---

lib/solidus_subscriptions/config.rb
lib/solidus_subscriptions/engine.rb
lib/solidus_subscriptions/permitted_attributes.rb

Updates the attributes that are permitted by default to match the new capabilities of the extension.

Update default permitted attributes

---

app/views/spree/admin/subscriptions/_form.html.erb
app/views/spree/admin/subscriptions/index.html.erb
lib/solidus_subscriptions/processor.rb

Use Spree.user_class instead of Spree::User to allow for custom user classes

---

app/controllers/spree/admin/subscriptions_controller.rb
app/models/solidus_subscriptions/line_item.rb
app/models/solidus_subscriptions/subscription.rb
spec/models/solidus_subscriptions/subscription_spec.rb

Adjusts the hooks and payloads for a few events in order to make event tracking more useful.

Improve event tracking

---

db/migrate/20200917072152_add_subscription_reference_to_orders.rb

Fixes an issue where a foreign key was being generated with a type incompatible with the foreign column in MySQL.

Fix foreign key type for MySQL

---

lib/generators/solidus_subscriptions/install/templates/initializer.rb

Improves the structure and documentation of the generated initializer.

Reformat sample configuration file

---

README.md
app/decorators/models/solidus_subscriptions/spree/wallet_payment_source/report_default_change_to_subscriptions.rb
app/models/solidus_subscriptions/subscription.rb
app/services/solidus_subscriptions/payment_failed_dispatcher.rb
app/services/solidus_subscriptions/success_dispatcher.rb
app/subscribers/solidus_subscriptions/churn_buster_subscriber.rb
config/initializers/subscribers.rb
lib/generators/solidus_subscriptions/install/templates/initializer.rb
lib/solidus_subscriptions.rb
lib/solidus_subscriptions/churn_buster/client.rb
lib/solidus_subscriptions/churn_buster/order_serializer.rb
lib/solidus_subscriptions/churn_buster/serializer.rb
lib/solidus_subscriptions/churn_buster/subscription_customer_serializer.rb
lib/solidus_subscriptions/churn_buster/subscription_payment_method_serializer.rb
lib/solidus_subscriptions/churn_buster/subscription_serializer.rb
lib/solidus_subscriptions/configuration.rb
solidus_subscriptions.gemspec
spec/fixtures/cassettes/churn_buster.yml
spec/lib/solidus_subscriptions/churn_buster/client_spec.rb
spec/lib/solidus_subscriptions_spec.rb
spec/models/solidus_subscriptions/subscription_spec.rb
spec/models/spree/wallet_payment_source_spec.rb
spec/services/solidus_subscriptions/payment_failed_dispatcher_spec.rb
spec/services/solidus_subscriptions/success_dispatcher_spec.rb
spec/subscribers/solidus_subscriptions/churn_buster_subscriber_spec.rb
spec/support/vcr.rb

Integrates [Churn Buster](https://churnbuster.com) natively in the extension, starting and stopping campaigns as a subscription fails/succeeds payment.

Integrate Churn Buster

---

app/models/solidus_subscriptions/subscription.rb
config/locales/en.yml
db/migrate/20210205140422_add_currency_to_subscription.rb
lib/solidus_subscriptions/checkout.rb
lib/solidus_subscriptions/subscription_generator.rb
lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
spec/lib/solidus_subscriptions/checkout_spec.rb
spec/lib/solidus_subscriptions/subscription_generator_spec.rb
spec/models/solidus_subscriptions/subscription_spec.rb

PR for #138 
Add `currency` to subscription and set it on every order.

Add currency to subscriptions

---

app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb
config/locales/en.yml
config/routes.rb
spec/jobs/solidus_subscriptions/process_installment_job_spec.rb
spec/requests/api/v1/subscriptions_spec.rb

Add a subscription *create* endpoint using the same logic of the *update* endpoint.
Closes #122.

Setup the subcription create endpoint

---

solidus_subscriptions.gemspec

This PR is sponsored by [MagmaLabs](https://www.magmalabs.io/)

support ruby 3

---

app/views/spree/admin/shared/_subscription_sidebar.html.erb

This PR adds a link to the user owning the subscription in the sidebar.

Link to the user in the subscription details sidebar

---

.circleci/config.yml
Gemfile
config/initializers/subscribers.rb
lib/solidus_subscriptions/engine.rb
solidus_subscriptions.gemspec
spec/controllers/spree/api/users_controller_spec.rb
spec/decorators/controllers/solidus_subscriptions/spree/orders_controller/create_subscription_line_items_spec.rb

Ref: https://github.com/solidusio-contrib/solidus_subscriptions/pull/261#issuecomment-1210294061

Restore running specs for solidus master

---

.rubocop.yml
README.md
spec/features/admin/subscriptions_spec.rb

The API link was removed since it's no longer active.
- Fixes #266 
The following are not always needed (~cross them out~ if they are not):

Update README links

---

app/models/solidus_subscriptions/subscription.rb
app/views/spree/admin/subscriptions/index.html.erb
spec/models/solidus_subscriptions/subscription_spec.rb

Added a way for admins to filter subscriptions by line item

---

solidus_subscriptions.gemspec

We need to release a new patch version after this one.
- 📖 I have updated the README to account for my changes.
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

Support Solidus v4

---

.circleci/config.yml
README.md

- 📖 I have updated the README to account for my changes.
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

Update to new "main" default branch
