solidusio/solidus_subscriptions

.travis.yml
1.14 has dependency resolution problems causing pre rails 5 builds to
fail
=> Lock travis bundler version

apidoc/docs/configuration.md, app/models/solidus_subscriptions/installment.rb, spec/models/solidus_subscriptions/installment_spec.rb
By default, when installments fail to be processed for any reason, they
are rescheduled to be reprocessed at a later date.
If the Config.reprocessing_interval field is set to nil, the installment
will not be reprocessed if it fails
=> Allow Failed installments to not be reprocessed

lib/solidus_subscriptions/engine.rb
Previous Behaviour:
The to_prepare block was reloading the permitted attributes module. This
resulted in the subscription parameters being appended to the spree
premitted attributes multiple times.
New behaviour:
Do not auto load the lib directory
Only load the permitted attributes once during the initalization process
=> Only load permitted attributes once

app/models/solidus_subscriptions/line_item.rb, app/models/solidus_subscriptions/subscription.rb
There is no need to delegate this to the associated line item. This
value will be persisted on the subscription once an order is completed
(or the subscription is created through the administrative interface)
=> Subs track their own interval now

lib/solidus_subscriptions/engine.rb
Only show the admin sidebar link if the user is authorized to see it.
Before:
The link to the subscriptions area of the subscriptions administrative
area would be displayed on the admin login screen.
Clicking this link without authenticating would redirect the user to the
log in page
After:
The link to the subscriptions area of the admin is hidden until after
the user authenticates
=> Authorize subscriptions admin sidebar link

app/views/spree/admin/solidus_subscriptions/subscriptions/_subscription.html.erb, config/locales/en.yml
It's always felt off that the cancel button was a "pause" icon and happened without confirmation. This updates it to be a "stop" icon (restarting is a "play" icon), which seems to be the right level of destructive to me. More than pause, less than trash can.
Also adds a confirmation dialog. Although the subscription can easily be restarted, it's conceivable that a store hooks in a cancelation email and it would be nice to double check that they actually want to cancel. This also follows the Solidus Orders admin, which confirms via a dialog (it can also be restarted).
This is all very much just opinion.
=> Small UI change to canceling in the admin

app/decorators/spree/orders/finalize_creates_subscriptions.rb, app/models/solidus_subscriptions/installment.rb, app/models/solidus_subscriptions/installment_detail.rb, app/models/solidus_subscriptions/interval.rb, app/models/solidus_subscriptions/line_item_builder.rb, app/models/solidus_subscriptions/order_builder.rb, app/models/solidus_subscriptions/out_of_stock_dispatcher.rb, app/models/solidus_subscriptions/payment_failed_dispatcher.rb, app/models/solidus_subscriptions/subscription.rb, app/models/solidus_subscriptions/subscription_promotion_rule.rb, app/models/solidus_subscriptions/success_dispatcher.rb
Just over here picking on the little things.
I am going to go over the documentation next and at that point will consider regenerating the YARD docs. It looks like it has been awhile since they have been generated.
=> Fix typos in comments

solidus_subscriptions.gemspec
ffaker was removed as a runtime dependency of Solidus. As of right now,
this removal is only on Solidus master (but it is slated for v2.4).
Even though this extension does not use ffaker directly, Solidus
complains that its factories require the library and so the tests fail
without this.
PR removing ffaker from Solidus:
https://github.com/solidusio/solidus/pull/2163
**EDIT**: The tests actually fail because of `require ffaker` in `spec/spec_helper.rb`. But even removing this line will cause the tests to fail in the way described above.
=> Add ffaker dependency to gemspec

.travis.yml
Bring solidus versions being tested up to date, to match what is shown
on https://extensions.solidus.io/.
=> Update solidus version for travis

apidoc/api/v1/subscription_line_items.md, apidoc/api/v1/subscriptions.md
Because of the way we mount this extension, we have to specify 'subscription' before the url (https://github.com/solidusio-contrib/solidus_subscriptions/blob/b2275c71fed698e9d33c89e428dd094a1338a5e9/config/routes.rb#L16). We should consider changing the way this is mounted but for now I have edited the documentation.
=> Change api url in documentation

solidus_subscriptions.gemspec
RuboCop 0.48.1 and earlier does not use `/tmp` in safe way, allowing local users to exploit this to tamper with cache files belonging to other users.
See [CVE-2017-8418](https://nvd.nist.gov/vuln/detail/CVE-2017-8418) for details.
=> Update rubocop to fix vulnerability CVE-2017-8418

.rubocop.yml, .travis.yml
Following #63, this PR aims to fix Travis build by doing the following:
* Not running `rubocop` on Travis (as per @kennyadsl's suggestion)
It also fixes namespacing issues on the `.rubocop.yml` file
=> Do not run rubocop on Travis

lib/solidus_subscriptions/testing_support/factories/installment_detail_factory.rb, lib/solidus_subscriptions/testing_support/factories/installment_factory.rb, lib/solidus_subscriptions/testing_support/factories/line_item_factory.rb, lib/solidus_subscriptions/testing_support/factories/spree/line_item_factory.rb, lib/solidus_subscriptions/testing_support/factories/spree/order_factory.rb, lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
FactoryBot 5.0 will no longer support static factory attributes, so we
need to update our factories in advance to silence the deprecation
warnings.
=> Change static factory attrs to dynamic

solidus_subscriptions.gemspec, spec/spec_helper.rb
FactoryBot v5.0 defaults `use_parent_strategy` to true, which builds (rather than create) associations, which was causing several specs to fail.
This PR also addresses an issue with SQLite (see commit ea118a2 for details)
=> Fix broken factories associations

app/views/spree/admin/subscriptions/index.html.erb
Most of the fields that allow sorting in the admin have a natural
order (id, created_at, etc), so sorting on them asc/desc makes sense
and works. However, fields like "state" and "processing", will only
have no natural ordering and sorting on them will only group them
together. This is really stange when you're paginating because records
on page 2, can come back up on page 3.
This fixes that by adding a second ordering by id: :asc on those fields.
=> Fixes admin sorting on fields without a natural order

app/models/solidus_subscriptions/checkout.rb
Removes a deprecated call to `SolidusSupport.solidus_gem_version` in favor of `Spree.solidus_gem_version`.
=> Fix deprecated call to `SolidusSupport.solidus_gem_version`

spec/models/solidus_subscriptions/subscription_spec.rb
Turns an `around(:all)` into `around`. `around(:all)` is not really supported by RSpec and is converted into `around(:example)` internally.
=> Fix unsupported `around(:all)` RSpec configuration

app/views/spree/admin/subscriptions/_form.html.erb
Adds a missing "Store" field in the subscription creation form, which is required for subscriptions. On the frontend, the store is set automatically from the store of the order, but on the backend it needs to be specified manually because subscriptions are not generated from an order.
=> Add store field to subscription creation UI

.github_changelog_generator
Adds a sensible configuration for github_changelog_generator that excludes issues and infrastructure PRs.
=> Add github_changelog_generator configuration

app/controllers/spree/admin/subscriptions_controller.rb, app/models/solidus_subscriptions/subscription.rb, app/views/spree/admin/subscriptions/_form.html.erb, config/locales/en.yml, spec/controllers/spree/admin/subscriptions_controller_spec.rb
Adds a "Remove?" checkbox to subscription line items in the subscription edit page in the backend. If checked, this will remove the line item from the subscription.
=> Allow admins to remove subscription line items

app/controllers/spree/admin/subscriptions_controller.rb, app/views/spree/admin/subscriptions/_form.html.erb
Subscriptions require a valid address in order to be processed, so we must include the address in the subscription form in the backend.
=> Add shipping address to backend subscription form

app/controllers/spree/admin/installments_controller.rb, app/controllers/spree/admin/subscriptions_controller.rb, app/models/solidus_subscriptions/installment.rb, app/views/spree/admin/installments/_state_pill.html.erb, app/views/spree/admin/installments/index.html.erb, app/views/spree/admin/shared/_subscription_actions.html.erb, app/views/spree/admin/shared/_subscription_breadcrumbs.html.erb, app/views/spree/admin/shared/_subscription_sidebar.html.erb, app/views/spree/admin/shared/_subscription_tabs.html.erb, app/views/spree/admin/subscriptions/_form.html.erb, app/views/spree/admin/subscriptions/_processing_state_pill.html.erb, app/views/spree/admin/subscriptions/_state_pill.html.erb, app/views/spree/admin/subscriptions/edit.html.erb, app/views/spree/admin/subscriptions/index.html.erb, config/locales/en.yml, config/routes.rb
Makes the subscription page on the backend much more informative by adding a sidebar that displays the subscription's status and actions on the edit page and an entire new section for displaying the installments of a subscription, along with their status.
=> Add subscription details to backend

app/controllers/spree/admin/subscriptions_controller.rb, app/models/solidus_subscriptions/subscription.rb, spec/lib/solidus_subscriptions/processor_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb
Uses the end date on the subscription, and not the line item, to determine whether a subscription can be deactivated.
The previous implementation looks like a leftover from times when subscriptions only had one line item and the line item stored information about the subscription's interval and end date. That information has since been moved to the `Subscription` model.
This also allows us to display subscriptions that don't have a line item in the admin list, which was previously impossible because the app would crash since it was calling `#can_be_deactivated?`, which in turn would try to call `#end_date` on a non-existing line item.
Note that this may potentially be a breaking change.
=> Use subscription's `end_date` in `Subscription#can_be_deactivated?`

app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb, app/controllers/spree/admin/subscriptions_controller.rb, app/models/solidus_subscriptions/line_item.rb, app/models/solidus_subscriptions/subscription.rb, app/services/solidus_subscriptions/checkout.rb, app/services/solidus_subscriptions/subscription_generator.rb, app/views/spree/admin/subscriptions/_form.html.erb, db/migrate/20200617102749_add_billing_address_to_subscriptions.rb, lib/solidus_subscriptions/factories.rb, lib/solidus_subscriptions/processor.rb, lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb, reference/solidus_subscriptions.v1.yaml, spec/controllers/solidus_subscriptions/api/v1/subscriptions_controller_spec.rb, spec/lib/solidus_subscriptions/processor_spec.rb, spec/models/solidus_subscriptions/line_item_spec.rb, spec/services/solidus_subscriptions/checkout_spec.rb, spec/services/solidus_subscriptions/subscription_generator_spec.rb, spec/spec_helper.rb, spec/support/factories.rb
Closes #117.
Adds the ability for users and admins to set the billing address on their subscription:
- When creating a subscription on the backend, the billing address is set directly on the subscription through the backend UI.
- When creating a subscription on the storefront or via the API, the billing address is copied from the order, just like what happens for the shipping address.
The subscription processing logic has also been adjusted slightly in order to:
- group subscription processing jobs by both shipping and billing address, and
- use either the subscription's billing address or the user's default billing address when processing a subscription.
=> Allow setting a billing address on the subscription

app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb, reference/solidus_subscriptions.v1.yaml
Closes #118.
Allows users to set the interval and end date of their subscriptions via the API. This is required because we're not respecting the interval and end date of subscription line items anymore (see #114).
=> Allow setting subscription interval and end date via the API

app/assets/javascripts/spree/backend/solidus_subscriptions.js, app/assets/javascripts/spree/backend/solidus_subscriptions/edit_subscription_payment.js, app/controllers/spree/admin/subscriptions_controller.rb, app/models/solidus_subscriptions/subscription.rb, app/services/solidus_subscriptions/checkout.rb, app/services/solidus_subscriptions/subscription_generator.rb, app/views/spree/admin/subscriptions/_form.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200617155042_add_payment_source_to_subscriptions.rb, db/migrate/20200618092951_add_payment_method_to_subscriptions.rb, spec/models/solidus_subscriptions/subscription_spec.rb, spec/services/solidus_subscriptions/checkout_spec.rb, spec/services/solidus_subscriptions/subscription_generator_spec.rb
Closes #116.
Implements the ability to have different payment methods and sources on each subscription. The payment information is copied from the order that originated the subscription, when possible.
Because the payment method is also stored, this PR also opens up the possibility of charging subscriptions via non-credit-card payment methods such as checks or wire transfers. All you have to do is set the right `payment_method` on the subscription and not set the `payment_source`.
=> Store payment method and source on subscriptions

app/decorators/models/solidus_subscriptions/spree/product/delegate_subscribable.rb, app/models/solidus_subscriptions/subscription.rb, app/overrides/views/admin_subscribable_product_checkbox.rb, app/overrides/views/admin_subscribable_variant_checkbox.rb, app/views/spree/admin/products/_subscribable_checkbox.html.erb, lib/generators/solidus_subscriptions/install/install_generator.rb, solidus_subscriptions.gemspec, spec/models/solidus_subscriptions/subscription_spec.rb, spec/services/solidus_subscriptions/subscription_generator_spec.rb, spec/services/solidus_subscriptions/subscription_promotion_rule_spec.rb
Closes #130.
Allows administrators to mark the master variant of a product as subscribable.
=> Allow admins to make master variants subcribable

lib/solidus_subscriptions/testing_support/factories/installment_factory.rb, lib/solidus_subscriptions/testing_support/factories/line_item_factory.rb, lib/solidus_subscriptions/testing_support/factories/spree/line_item_factory.rb, lib/solidus_subscriptions/testing_support/factories/spree/order_factory.rb, lib/solidus_subscriptions/testing_support/factories/subscription_factory.rb
Adjusts the factories to always use `association` when building associated records. This fixes a weird bug that would occur when creating a `subscription_line_item` (and potentially others).
=> Use parent strategy when building associations in factories

app/controllers/spree/admin/subscription_events_controller.rb, app/models/solidus_subscriptions/line_item.rb, app/models/solidus_subscriptions/subscription.rb, app/models/solidus_subscriptions/subscription_event.rb, app/views/spree/admin/shared/_subscription_tabs.html.erb, app/views/spree/admin/subscription_events/_state_pill.html.erb, app/views/spree/admin/subscription_events/index.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200730101242_create_solidus_subscriptions_subscription_events.rb, lib/solidus_subscriptions/testing_support/factories/subscription_event_factory.rb, spec/models/solidus_subscriptions/line_item_spec.rb, spec/models/solidus_subscriptions/subscription_event_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb
Implements a simple `SubscriptionEvent` model to keep track of different events in a subscription's lifecycle (cancellations, reactivations etc.) These events can then be seen on the subscription page in the backend.
The events are also emitted via `Spree::Event` when it's available.
=> Subscription events

app/decorators/models/solidus_subscriptions/spree/order/subscription_association.rb, app/models/solidus_subscriptions/subscription.rb, app/services/solidus_subscriptions/checkout.rb, db/migrate/20200917072152_add_subscription_reference_to_orders.rb
This PR adds a bi-directional `order` association towards `SolidusSubscriptions::Subscription`. This helps in cases we'd need to access easily orders related to a subscription and vice-versa.
=> Add order association to subscriptions

app/models/solidus_subscriptions/line_item.rb, lib/generators/solidus_subscriptions/install/templates/initializer.rb, lib/solidus_subscriptions/configuration.rb
This paves the way for integrating with [solidus_tracking](https://github.com/solidusio-contrib/solidus_tracking), which needs access to the subscribable object in order to serialize it.
=> Implement a `LineItem#subscribable` association

app/services/solidus_subscriptions/dispatcher.rb, app/services/solidus_subscriptions/failure_dispatcher.rb, app/services/solidus_subscriptions/out_of_stock_dispatcher.rb, app/services/solidus_subscriptions/payment_failed_dispatcher.rb, app/services/solidus_subscriptions/success_dispatcher.rb, spec/services/solidus_subscriptions/dispatcher_spec.rb, spec/services/solidus_subscriptions/failure_dispatcher_spec.rb, spec/services/solidus_subscriptions/out_of_stock_dispatcher_spec.rb, spec/services/solidus_subscriptions/payment_failed_dispatcher_spec.rb, spec/services/solidus_subscriptions/success_dispatcher_spec.rb
Streamlines the dispatchers API by fixing some typos in the API documentation.
This PR also removes the built-in logging functionality, which can be easily added back in by the user if needed. Logging at the INFO level out of the box can easily pollute the logs of high-volume eCommerce applications.
=> Improve dispatchers API

app/models/solidus_subscriptions/line_item.rb, app/subscribers/solidus_subscriptions/event_storage_subscriber.rb, spec/models/solidus_subscriptions/line_item_spec.rb
This event is not really useful in its current form. Instead, each store should track repopulation in a way that makes sense for them.
=> Remove subscription_repopulated event

app/controllers/spree/admin/subscriptions_controller.rb, bin/rails-sandbox, config/initializers/permission_sets.rb, lib/solidus_subscriptions.rb, lib/solidus_subscriptions/permission_sets/default_customer.rb, lib/solidus_subscriptions/permission_sets/subscription_management.rb, spec/lib/solidus_subscriptions/permission_sets/default_customer_spec.rb, spec/lib/solidus_subscriptions/permission_sets/subscription_management_spec.rb
Adds an ActiveRecord scope to our default permission set, so that `#accessible_by` can be used with `SolidusSubscriptions::Subscription` once more.
=> Add scope to permission set

app/models/solidus_subscriptions/installment.rb, app/models/solidus_subscriptions/subscription.rb, lib/generators/solidus_subscriptions/install/templates/initializer.rb, lib/solidus_subscriptions/configuration.rb, spec/models/solidus_subscriptions/installment_spec.rb
Adds a preference that allows the user to specify the maximum number of times the system should attempt to reprocess a subscription that failed payment before cancelling it.
=> Add maximum_reprocessing_attempts preference

app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb, app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb, bin/rails-sandbox, lib/solidus_subscriptions/permission_sets/default_customer.rb, spec/lib/solidus_subscriptions/permission_sets/default_customer_spec.rb
Fixes an issue with the DefaultCustomer permission set, which allowed guest users to access the subscription admin page (although they wouldn't have access to any subscriptions).
=> Fix DefaultCustomer permission set giving guests access to admin

app/controllers/spree/admin/users/subscriptions_controller.rb, app/overrides/views/admin_users_subscriptions_tab.rb, app/views/spree/admin/shared/_subscription_tab.html.erb, app/views/spree/admin/users/_subscription_tab.html.erb, app/views/spree/admin/users/subscriptions/index.html.erb, config/locales/en.yml, config/routes.rb, lib/solidus_subscriptions/engine.rb, spec/features/admin_users_subscription_tabs_spec.rb
It adds a simplified version of the Subscription list to the user's show page. This is intended to make it easier to list user's subscriptions when accessing their pages.
=> Add Subscriptions tab to User page in Admin

app/models/solidus_subscriptions/installment.rb, app/models/solidus_subscriptions/subscription.rb, lib/generators/solidus_subscriptions/install/templates/initializer.rb, lib/solidus_subscriptions/configuration.rb, spec/models/solidus_subscriptions/installment_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb
This changes the logic used to determine whether a subscription should be canceled after consecutive payment failures. Previously it was based on a maximum number of attempts per installment, however it makes sense to have it based on the time passed since the last succesful installment.
This makes it also play nice with the [new configuration](https://github.com/solidusio-contrib/solidus_subscriptions/commit/b3dc679b7056931397820ad333686ef151656ba4) to clear past failed installments, which could render the maximum attempts useless, since there could have been situations where the maximum attempts number would never be reached. Switching to time based criteria makes this simpler and more predictable.
=> Move maximum reprocessing retries to a time based criterion

app/models/solidus_subscriptions/installment.rb, app/models/solidus_subscriptions/installment_detail.rb, app/models/solidus_subscriptions/subscription.rb, spec/lib/solidus_subscriptions/processor_spec.rb, spec/models/solidus_subscriptions/installment_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb, spec/support/helpers/config.rb
Fixes an issue with automatic subscription cancellation that was causing subscriptions to be cancelled ahead of time.
Rather than looking at the date of the first failed payment, we were looking at the date of the last successful payment. This means that, if a customer was on a 4-week cycle and a payment failed, the system would assume that payment had been failing for 4 weeks, where in fact it had just started failing.
The new implementation looks at the date of the first failed charge after the last successful charge, which is the behavior we expected.
=> Fix automatic cancellation in case of subscription failure

app/models/solidus_subscriptions/installment.rb, app/models/solidus_subscriptions/subscription.rb, app/views/spree/admin/subscriptions/index.html.erb, app/views/spree/admin/users/subscriptions/index.html.erb, db/migrate/20201123171026_change_actionable_date_to_date.rb, spec/decorators/models/solidus_subscriptions/spree/order/finalize_creates_subscrptions_spec.rb, spec/models/solidus_subscriptions/installment_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb, spec/services/solidus_subscriptions/checkout_spec.rb
Removes the time component from the actionable_date column, both on subscriptions and installments. This can easily create bugs where the actionable_date of a subscription or installment is equal to the current date, but the time is in the future, and that causes the subscription/installment not to be processed.
=> Remove time component from actionable_date columns

Gemfile, README.md, app/models/solidus_subscriptions/subscription.rb, lib/solidus_subscriptions/configuration.rb, spec/models/solidus_subscriptions/subscription_spec.rb
Previously, the cancel method would add one day to your
minimum_cancellation_date. This updates that! More info here:
https://github.com/solidusio-contrib/solidus_subscriptions/issues/177
=> Update cancel method on subscription to respect minimum date

app/models/solidus_subscriptions/installment.rb, lib/solidus_subscriptions/processor.rb, spec/lib/solidus_subscriptions/processor_spec.rb
Anyone who cancels their subscription with a failed installment will
still have an order created the next time installments are created.
This is because installments don't check the status of their associated
subscriptions before being processed.
This update will ensure that only active subscriptions are processed.
Ref: #180
=> Avoid processing installments with cancelled subscriptions

app/decorators/models/solidus_subscriptions/spree/order/installment_details_association.rb, spec/decorators/models/solidus_subscriptions/spree/order/installment_details_association_spec.rb
This is useful if you want to connect orders to installments - for
instance, if you wanted to get a list of orders for a user that
are part of an installment.
=> Add Installment Details association to Order

app/views/spree/admin/users/_subscription_tab.html.erb
Previously, it would check your permissions on an ActiveRecord
association - which would in most non-admin cases be false, even
if they had permissions to manage subscriptions. This changes the
check to return a new instance of the users subscriptions, so
people with manage subscriptions permissions will still be able
to view this tab, while also allowing for you to conditionally
allow/deny permissions based on what users subscriptions they
are attempting to view.
=> Update permissions check on user subscription tab

Gemfile, app/models/solidus_subscriptions/installment.rb, spec/lib/solidus_subscriptions/processor_spec.rb
The `canonical-rails` was locked down to 0.2.9 because Solidus still used the `whitelisted_attributes` method but with the new version 0.2.10 it was renamed to `allowed_parameters` and it can be removed.
This fixes https://github.com/solidusio-contrib/solidus_subscriptions/issues/187.
=> Remove "canonical-rails" from the Gemfile

config/locales/en.yml
Fixes some typos on the notification messages for subscription created, activated, and skipped.
=> Fix typo in subscription admin notifications

app/models/solidus_subscriptions/subscription.rb, spec/models/solidus_subscriptions/subscription_spec.rb
Increments `skip_count` and `successive_skip_count` Subscription attributes when `SolidusSubscriptions::Subscription#skip` is called so the skip limits are correctly handled.
This should fix https://github.com/solidusio-contrib/solidus_subscriptions/issues/146
=> Fix skip counters to handle skip limits

app/models/solidus_subscriptions/installment.rb
`SolidusSubscriptions::Installment#unfulfilled` gets the list of fulfilled installments, loads them ALL into memory, and then performs a WHERE id NOT IN (...) to get the installments that were not fulfilled, this PR simplify the scope using a WHERE clause with a subquery.
This fixes #171.
=> Improve "unfulfilled" scope by adding subquery

app/decorators/models/solidus_subscriptions/spree/user/have_many_subscriptions.rb, spec/decorators/models/solidus_subscriptions/spree/user/have_many_subscriptions_spec.rb
This PR comes as a temporary solution for #124. 
Since removing `Spree::User` subscriptions `nested_attributes` directly may cause problems to current users of the extension, they have just been deprecated right now, so that they can be removed from next releases.
=> Deprecate nested subscription attributes from user

bin/sandbox
I run `solidus extension .` (after running `bundle`) but kept only the change to `bin/sandbox`
Closes #196.
=> Fix sandbox creation error

lib/solidus_subscriptions/churn_buster/subscription_customer_serializer.rb
Solidus 3.0 removes `first_name` and `last_name` from `Spree::Address`
so we should replace them with `name`. The Churn Buster documentation
would suggest it's OK to pass any customer properties we need, but I
have yet to get a developer account to verify.
Leaving this in draft until I can verify with a Churn Buster developer account.
Closes #194.
=> Use `name` in customer serializer

app/controllers/spree/admin/subscriptions_controller.rb, spec/controllers/spree/admin/subscriptions_controller_spec.rb
Ref: #132 
When we update a subscription with new line items, the logic is assigning it twice. It's assigned in SubscriptionsController#update[1] and in ResourceController#update[2].
It only happened with new line items because there's no id for them.
[1] https://github.com/solidusio-contrib/solidus_subscriptions/blob/69f0ca038b66d0ca36971405e51c0d3aa916cf19/app/controllers/spree/admin/subscriptions_controller.rb#L28
[2] https://github.com/solidusio/solidus/blob/b0092d0f3bda447494a586bf8eb96a18322b8bed/backend/app/controllers/spree/admin/resource_controller.rb#L36
=> Fix duplicated line items creation

lib/solidus_subscriptions/subscription_generator.rb, spec/lib/solidus_subscriptions/subscription_generator_spec.rb
In this PR I'm going to implement the second solution proposed in the issue because I think that if those fields on the source have completed their goal and we don't need them anymore on the line items it is conceptually good to *move* them in the subscription. And it also seems to me the way less prone to unexpected side effects/bugs (keep it simple).
Closes #114.
=> Cleanup the duplicated fields on subscription creation

app/controllers/spree/admin/subscription_orders_controller.rb, app/views/spree/admin/shared/_subscription_tabs.html.erb, app/views/spree/admin/subscription_orders/index.html.erb, config/locales/en.yml, config/routes.rb, spec/features/admin/subscription_orders_spec.rb
Add a new tab in the member view of subscriptions to list the orders
processed by the current subscription.
Closes #129
=> Admin: expose the subscription orders

lib/solidus_subscriptions/testing_support/factories.rb, spec/spec_helper.rb
This will load factories using `FactoryBot.find_definitions` for Solidus versions that support it, otherwise it fallbacks on the old way (manually requiring factories).
=> Load factories using the new standard

app/jobs/solidus_subscriptions/process_subscription_job.rb, app/models/solidus_subscriptions/subscription.rb, lib/solidus_subscriptions/processor.rb, spec/jobs/solidus_subscriptions/process_subscription_job_spec.rb, spec/lib/solidus_subscriptions/processor_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb
Ref #190 
This PR aims to move the processing of individual subscriptions to their own isolated jobs. The tasks of these individual jobs will be:
- Deactivate/Cancel subscriptions pending one of those operations
- Clear any past failed installment if it's configured to do so
- Create a new installment for the subscription cycle
- Enqueue a job to process any actionable installment for the subscription
Given we've moved the concern of queueing the installment processing, that part can be removed safely from the main processor job.
The final part of the change also touches the main processor job, whose task is now to collect any actionable subscription **AND** any subscription with an actionable installment to enqueue them for individual processing.
=> Move subscription processing to its own background job

solidus_subscriptions.gemspec
This is required in Solidus v2.11+, otherwise the extensions' subscriber won't be loaded automatically.
Related https://github.com/solidusio-contrib/solidus_subscriptions/commit/5b1795151eb52ec8c5097f3ad58db055d9acb1bb.
=> Require a version of solidus_support that autoloads subscribers

README.md, app/decorators/models/solidus_subscriptions/spree/variant/auto_delete_from_subscriptions.rb, spec/decorators/models/solidus_subscriptions/spree/variant/auto_delete_from_subscriptions_spec.rb
This should fix #133
In this PR, when a `Spree::Variant` is soft-deleted, its related subscription line items are deleted too.
If the product class is not a `Spree::Variant`, the variant subscription line items deletion should be handled manually.
=> Remove variant from subscriptions on soft deletion

lib/solidus_subscriptions/permission_sets/default_customer.rb, spec/lib/solidus_subscriptions/permission_sets/default_customer_spec.rb
Although an effort to grant a seamless transition has been done, this change is still necessary because of the many places in which `can? :display` has become `can? :show` or `can? :read`.
Ref: https://github.com/solidusio/solidus/pull/3701
=> Add missing permissions sets for Solidus v2.11

app/models/solidus_subscriptions/subscription.rb, config/locales/en.yml, spec/features/admin/subscriptions_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb
This fixes #207, setting the currency value to the default `Spree::Config` one.
It also adds a UI test for subscription creation from admin panel.
=> Set default config currency to subscription

app/jobs/solidus_subscriptions/process_installment_job.rb, lib/generators/solidus_subscriptions/install/templates/initializer.rb, lib/solidus_subscriptions/configuration.rb, spec/jobs/solidus_subscriptions/process_installment_job_spec.rb
Fixes https://github.com/solidusio-contrib/solidus_subscriptions/issues/175
This disables the ActiveJob default retry mechanism because installment
processing failures are already taken care of by solidus_subscriptions.
Before this, there was a potential for double retrying, which could
causes background jobs and canceled orders to accumulate leading
to side effects and a bad customer experience.
Now, a `process_job_error_handler` configuration Proc is called when a
ProcessInstallmentJob `#perfom` method fails.
The rescued error can be managed/logged as preferred or re-raised
if the default retry behavior is required in the ProcessInstallmentJob.
=> Skip ActiveJob retrying for ProcessInstallmentJob

db/migrate/20210323165714_update_promotion_rule_names.rb
After https://github.com/solidusio-contrib/solidus_subscriptions/pull/215, update promotion rule names on db to avoid STI errors.
=> Update promotion rule names on db

app/models/solidus_subscriptions/subscription.rb, config/locales/en.yml, spec/controllers/spree/admin/subscriptions_controller_spec.rb, spec/lib/solidus_subscriptions/checkout_spec.rb, spec/lib/solidus_subscriptions/subscription_generator_spec.rb, spec/models/solidus_subscriptions/subscription_spec.rb
Closes #208
This PR adds a new validation in the Subscription model that verifies that the payment source used for the subscription (if specified explicitly) is owned by the same user that is on the subscription, as done in the [Solidus wallet](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/wallet_payment_source.rb#L26-L33). This will help prevent any bugs when the payment source for a subscription is accidentally set to another user's payment source.
=> Validate payment_source ownership on the subscription

app/decorators/models/solidus_subscriptions/spree/order/finalize_creates_subscriptions.rb, spec/decorators/models/solidus_subscriptions/spree/order/finalize_creates_subscriptions_spec.rb
If you decorate the subscription generator to change the order
in any way (for instance, to associate the order to the
subscription), that change is not persisted in the rest of the
finalize action, as the order has already been loaded by that
point.
This can cause massive headaches with validations, so to fix it
I've added a reload method before super, so we can ensure that
the order is up-to-date before continuing.
This also means that subscription_line_items interval is nil,
since activating the subscription sets it to nil. So in the spec
we're fetching the interval from the subscription instead.
=> Reload order during finalize action

app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb, lib/solidus_subscriptions/configuration.rb
This removes a filter on the api `SubscriptionsController `that made it impossible to add a subscribable_id to the nested line_item_attributes (effectively prohibiting the creation of LineItems on the creation of a Subscription.
This allows the api to be more flexible but still allows users to limit certain operations by customizing the `config.subscription_line_item_attributes`
=> Fix Api Subscription Permitted LineItem Attributes

lib/generators/solidus_subscriptions/install/templates/initializer.rb, lib/solidus_subscriptions.rb, lib/solidus_subscriptions/checkout.rb, lib/solidus_subscriptions/configuration.rb, lib/solidus_subscriptions/order_creator.rb
This adds both `SolidusSubscriptions.configuration.order_creation_class` and `SolidusSubscriptions.configuration.order_creation_extra attributes`, so that users can add attributes to each Installment Order at Checkout or even override how the Order is created.
=> Introduce Installment OrderCreator configuration

app/jobs/solidus_subscriptions/process_installment_job.rb, lib/generators/solidus_subscriptions/install/templates/initializer.rb, lib/solidus_subscriptions/configuration.rb, lib/solidus_subscriptions/engine.rb, lib/solidus_subscriptions/processing_error_handlers/rails_logger.rb, spec/jobs/solidus_subscriptions/process_installment_job_spec.rb
At the moment, by default, all installment processing errors are swallowed and there's no way for a developer to understand what's happening. Of course, they can create a custom handler with the `processing_error_handler` configuration provided but usually, when the first errors happen, it's too late and those errors are lost.
We are not raising errors of this job because if there's a retry mechanism in place for Active Job, the installment will be reprocessed twice. Once by Active Job and once by the installment retry mechanism already provided by the extension.
Logging to `Rails.error` is a middle-ground that allows to intercept the message of the exception. Still, creating a custom handler based on the bug tracker/exception handler used is the suggested option here.
This PR also …
=> Log installments errors by default

app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb, app/controllers/spree/admin/subscriptions_controller.rb, app/models/solidus_subscriptions/subscription.rb, app/views/spree/admin/shared/_subscription_actions.html.erb, app/views/spree/admin/subscriptions/_state_pill.html.erb, app/views/spree/admin/subscriptions/index.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20210905145955_add_paused_to_subscriptions.rb, lib/solidus_subscriptions/permission_sets/default_customer.rb, spec/models/solidus_subscriptions/subscription_spec.rb, spec/requests/api/v1/subscriptions_spec.rb
This change:
- Adds the ability to pause subscriptions for either a specified amount of time or an indefinite amount of time
- Adds endpoints to pause and resume subscriptions
- Integrates pause/resume buttons on the subscription admin page
Adds a `paused` boolean column to the `subscriptions` table.
- The `paused` attribute acts as a sub-state of `active`. This is a logical approach because `paused` subscriptions should still be considered `active`.
Subscriptions can be paused with a scheduled activation (corresponding to the `actionable_date`) or indefinitely (set the `actionable_date` to `nil`).
- The soonest allowed actionable date (for pausing and resuming) is the next day to avoid issues with processing subscriptions
- Subscriptions can also be resumed with a scheduled activation or …
=> Add ability to pause/resume subscriptions

app/models/solidus_subscriptions/subscription.rb, spec/models/solidus_subscriptions/subscription_spec.rb
Fixes a bug introduced in https://github.com/solidusio-contrib/solidus_subscriptions/commit/afbffbf65c2be3cd049b5cbd47c6de1d22c88554 where `update_columns` is used instead of `update!` when pausing and unpausing a subscription. This causes issues because `updated_at` does not change, and callbacks created in user applications will not run. 
Also improves a test for when the paused `actionable_date` is reached.
=> Bugfix update column when pausing

app/decorators/models/solidus_subscriptions/spree/order/finalize_creates_subscriptions.rb, lib/solidus_subscriptions/configuration.rb, lib/solidus_subscriptions/subscription_generator.rb, spec/decorators/models/solidus_subscriptions/spree/order/finalize_creates_subscriptions_spec.rb
Adds `SolidusSubscriptions.configuration.subscription_generator_class` as a callable that takes in an order instead of passing line items so that the generator can use a custom strategy.
=> Make the subscription generator a configurable class

app/models/solidus_subscriptions/subscription.rb, app/views/spree/admin/subscriptions/index.html.erb, spec/models/solidus_subscriptions/subscription_spec.rb
Fixes #274
This PR fixes the above issue by changing how the admin scopes subscriptions tied to a particular variant, instead of having to hunt down the specific line item when filtering them.
This also restructures the query in the view to avoid N+1s. On a store with 100K subscriptions the query and relative map take ~30ms.
The following are not always needed (~cross them out~ if they are not):
=> Fix filtering by line item in admin

.circleci/config.yml
ref #280 
Updates CircleCI config to run tests with Ruby 2.7, 3.0 and 3.1. It does not include all permutations of the DB options since they are pretty similar
📝 The specs are currently failing due to the issue with `solidus_frontend` not being compatible with `solidus` master (same failure on master)
The following are not always needed (~cross them out~ if they are not):
=> Run specs on Ruby 2.7, 3.0 and 3.1

lib/decorators/api/controllers/solidus_subscriptions/spree/api/line_items_controller/create_subscription_line_items.rb, spec/controllers/spree/api/line_items_controller_spec.rb
Closes #279 
`Spree::LineItem` already has defined in its model `accepts_nested_attributes_for :subscription_line_items` so we can leverage this to update a nested model of the line item.
The API call should be:
```
{
"line_item": {
"quantity": 1
}
"subscription_line_items_attributes": {
"id": {subscription_line_item_id}
"interval_length": 15,
}
}
```
This "strange" unnested format is required for the way we are updating line items in the API line_item controller: https://github.com/solidusio/solidus/blob/e878076f2ed670d07654ab6293a16588743f2fa6/api/app/controllers/spree/api/line_items_controller.rb#L29. 
The …
=> Allow updating subscription information in cart

.circleci/config.yml, app/subscribers/solidus_subscriptions/churn_buster_subscriber.rb, app/subscribers/solidus_subscriptions/event_storage_subscriber.rb, app/subscribers/solidus_subscriptions/order_subscriber.rb, lib/solidus_subscriptions/engine.rb
The old one has been removed on v4.0.
We'll need a major release after this change is merged.
See https://github.com/solidusio/solidus/pull/5024
We're also fixing CI with different changes to our CircleCI config:
- Run different Solidus versions on different jobs for better error handling.
- We're now explicitly providing the ruby version to the executor while using a matrix configuration for better extensibility.
- 📖 I have updated the README to account for my changes.
- 🛣️ I …
=> Only use the newer Solidus event system

app/models/solidus_subscriptions/promotion/rules/subscription_creation_order.rb, app/models/solidus_subscriptions/promotion/rules/subscription_installment_order.rb
While working on a client project and upgrading to Ruby 3, the mismatch in how the #eligible? is signed between solidus_core and solidus_subscriptions made some code break because Spree::Promotion#eligible_rules? doesn't double splat the options.
Before Ruby 3 the double splat would return a Hash, however with Ruby 3 those are kept as keyword arguments, breaking the method call site.
- 📖 I have updated the README to account for my changes.
- 🛣️ I have opened a PR to update the …
=> Update built in promotions #eligible? signature

README.md, bin/sandbox, lib/generators/solidus_subscriptions/install/install_generator.rb
Now that we have committed to the Starter StoreFront as the default, it may be confusing to see that this extension installs on the legacy one by default.
I have made some small changes to make the SSF the default. To install on the legacy Frontend, it must be specified explicitly.
[x] 📖 I have updated the README to account for my changes.
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes. …
=> Change default frontend

app/models/solidus_subscriptions/installment.rb, app/models/solidus_subscriptions/subscription.rb, app/models/solidus_subscriptions/subscription_event.rb
Issue - Runtime Error in Spree::Admin::Subscriptions. Ransack needs Solidus Subscriptions, Installments, Events attributes explicitly allowlisted as searchable 
Fixes - Added the methods to make subscriptions, installments, events attributes allowlisted as searchable.
- I have written a thorough PR description.
- I have kept my commits small and atomic.
- I have used clear, explanatory commit messages
- 📸 I have attached screenshots to demo visual changes.
=> Ransack searchable attribute issue in admin

app/models/solidus_subscriptions/line_item.rb, app/models/solidus_subscriptions/subscription.rb, config/locales/en.yml, db/migrate/20210323165714_update_promotion_rule_names.rb, lib/generators/solidus_subscriptions/install/install_generator.rb, lib/generators/solidus_subscriptions/install/templates/app/controllers/concerns/create_subscription.rb, lib/generators/solidus_subscriptions/install/templates/app/views/cart_line_items/_subscription_fields.html.erb, lib/solidus_subscriptions/engine.rb, solidus_subscriptions.gemspec, spec/controllers/concerns/create_subscription_spec.rb, spec/controllers/spree/api/line_items_controller_spec.rb, spec/controllers/spree/api/orders_controller_spec.rb, spec/decorators/controllers/solidus_subscriptions/spree/orders_controller/create_subscription_line_items_spec.rb, spec/jobs/solidus_subscriptions/process_subscription_job_spec.rb, spec/models/solidus_subscriptions/line_item_spec.rb
---
This PR introduces improvements and new features to the Solidus Subscriptions module, with a focus on subscription validation and handling subscription-related logic.
---
- A custom validation `ensure_subscribable_valid` is added to the `SolidusSubscriptions::LineItem` model. This validation ensures that only products marked as subscribable can be added to a subscription. If a product is not subscribable, an error is added to the `subscribable` field with the message "The requested item cannot be subscribed".
- Added an entry to `config/locales/en.yml` to define the error message for the subscribable validation ("The requested item cannot be subscribed").
- Updated the subscription form in `app/views/cart_line_items/_subscription_fields.html.erb` to display subscription fields …
=> Subscription api fix for subscribable product

spec/models/solidus_subscriptions/subscription_spec.rb, spec/spec_helper.rb
This spec is currently failing, because it implicitly depends on there not being February between now and the expected date. Fixing by pretending to be in the past.
=> Fix flaky subscription spec
